services:
  node:
    image: blackopsinc/blackscan:latest
    hostname: blackscan
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./data:/data
      - ./playbooks:/playbooks
      - ./modules:/modules
    restart: unless-stopped
    environment:
      - blackscan_domain=localhost
    deploy:
      mode: replicated
      replicas: 1
